### ISSUE TITLE
imagestream is not deleted when Component is deleted

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#113]
# Issue

The imageStream is not deleted when the Component resource is deleted. This is due to the fact that this code is never called: 
https://github.com/halkyonio/operator/blob/aaa8f3976556b029299a79f27194e75f3a9381ab/pkg/controller/component/controller.go#L138

This happens because when we delete a component, then the property `resource.ShouldDelete()` is never equal to true - https://github.com/halkyonio/operator/blob/aaa8f3976556b029299a79f27194e75f3a9381ab/pkg/controller/generic.go#L218

The `DeletionTimestamp` is `nil` when we call this line of code -> https://github.com/halkyonio/operator/blob/632eb4080e6349c40693885763678240ca7a6866/pkg/apis/halkyon/v1beta1/component_types.go#L173
but even if this code returns `true`

```
// IsZero returns true if the value is nil or time is zero.
func (t *Time) IsZero() bool {
	if t == nil {
		return true
	}
	return t.Time.IsZero()
}
```

`resource.ShouldDelete()` is still evaluated as false ...

Do you know why @metacosm ?

**Comment by metacosm** [comment]
I've noticed that `DeletionTimestamp` is never non-zero so the `shouldDelete` part and deletion logic doesn't really work. I think that we need finalizers for this to work.

**Comment by cmoulliard** [comment]
A `DeletionTimeStamp` is only added if I remember correctly with previous operator code for the ServiceCatalog, when a finalizer is used. In this case, our component will only be deleted when all the related resources will delete their resources and will remove from the finalizer string from the resource
