### ISSUE TITLE
OLM Category: Developer Tools vs Application Runtimes vs ...

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#115]
## Question

What should be the category to be used to define the operator within the OperatorHub ?
**Under Developer Tool** 

<img width="1416" alt="Screenshot 2019-08-23 07 06 53" src="https://user-images.githubusercontent.com/463790/63568295-ffccc980-c574-11e9-88f8-fd8e8e10c939.png">

or as **Application Runtime** (like the OpenLiberty Operator)

<img width="1433" alt="Screenshot 2019-08-23 07 06 42" src="https://user-images.githubusercontent.com/463790/63568269-e3c92800-c574-11e9-9cff-1509f776a31f.png">

WDYT @nainaz @metacosm @geoand @aureamunoz

**Comment by geoand** [comment]
Based on what is already in those categories, I would say that `Application Runtime` definetely is **not** the correct choise.

**Comment by cmoulliard** [comment]
+1 to use then `Developer Tools` as category

**Comment by cmoulliard** [comment]
Here is How it will look like when it will be deployed through the operator hub

![Screenshot 2019-08-23 11 30 49](https://user-images.githubusercontent.com/463790/63582539-8eebd880-c599-11e9-9a46-68a0aee05a09.png)
