### ISSUE TITLE
Releases don't include binaries

### ISSUE THREAD

**Issue by geoand** [halkyonio/operator#121]
## Issue

There is an issue as circleci is calling the [upload_assets.sh bash script ](https://github.com/halkyonio/operator/blob/ae0af9c30d6a32b1a0b7f0e018b874507039c8f0/scripts/upload_assets.sh#L74-L73)(using command : [make upload](https://github.com/halkyonio/operator/blob/master/.circleci/config.yml#L325)) to upload the artifacts to github but only the source code is uploaded and not anymore the binaries inder a release

New release: https://github.com/halkyonio/operator/releases/tag/v0.1.1
Old good: https://github.com/halkyonio/operator/releases/tag/v0.0.1

**Comment by geoand** [comment]
cc @cmoulliard

**Comment by geoand** [comment]
I know what the problem is, basically `git checkout` effectively "resets" the build directory. I'll fix it

**Comment by geoand** [comment]
Actually no, that is not the case...

**Comment by cmoulliard** [comment]
Problem is not fixed when I released 0.1.2

**Comment by geoand** [comment]
Do you have any ideas what is going on? I am out of ideas

**Comment by geoand** [comment]
I am looking at: https://github.com/halkyonio/operator/releases/tag/v0.0.2 and https://github.com/halkyonio/operator/releases/tag/v0.0.3 and they don't have the binaries either

**Comment by geoand** [comment]
When I do `make cross`, I see:

```
drwxrwxr-x 2 gandrian gandrian 4096 Αυγ  27 17:51 darwin-amd64
drwxrwxr-x 2 gandrian gandrian 4096 Αυγ  27 17:51 linux-amd64
drwxrwxr-x 2 gandrian gandrian 4096 Αυγ  27 17:51 release
``` 

But then when I do `ls -l ./build/_output/bin/release/`:

```
total 0
```

So it makes sense (based on the contents of `for arch in $(ls -1 $BIN_DIR/); do`) that no assets are uploaded.
I propose that you take over this one @cmoulliard since you were the one that wrote this part.

**Comment by cmoulliard** [comment]
> binaries either

only this release included them -> https://github.com/halkyonio/operator/releases/tag/v0.0.1

**Comment by cmoulliard** [comment]
> So it makes sense (based on the contents of `for arch in $(ls -1 $BIN_DIR/); do`) that no assets are uploaded.

The problem is not this bash_script but the circleci config file as the command `make cross` is defined with the job `build` which is not anymore executed and `release:` job don't include it ;-)
