### ISSUE TITLE
All the commits are included within the tag/release

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#125]
## Issue

Something wrong happens as all the commits are included when we do a release even if the delta includes 2-3 commits from last release. See: https://github.com/halkyonio/operator/releases/tag/v0.1.2

**Comment by geoand** [comment]
Yes I mentioned this in the chat.

I propose we don't do anything with this for the time being.
It will be difficult to fix because the tags are no longer built of master (but a temporary branch that is used to commit the changes to the files during release)

**Comment by geoand** [comment]
I opened a PR that hopefully solves problem.

If it doesn't I don't think there is anything else we can do to the fact that we have to do an actual commit to change files during the release process.
