### ISSUE TITLE
Release name contains 2 v letters

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#127]
## Issue

Release name contains 2 v letters --> `vv0.1.2`. See screenshot

<img width="994" alt="Screenshot 2019-08-28 22 44 41" src="https://user-images.githubusercontent.com/463790/63891467-8bb37b00-c9e5-11e9-87a1-324dbbd29b6f.png">

**Comment by geoand** [comment]
That was a mistake I made when I was testing the fix for the other issue
