### ISSUE TITLE
Feature: Backup /deployments

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#141]
## Feature

Backup the files uploaded under the folder `/deployments` using a volume mounted within the POD and a PVC in order to let the content to survive after a pod's killed

**Comment by cmoulliard** [comment]
The fix allows to mount the folder `/deployments` but as it will be mounted as `root`, we can't push using `oc or kubectl cp` command as a permission denied error will be reported
```
tar: fruit-client-sb-0.0.1-SNAPSHOT.jar: Cannot open: Permission denied
```

**Comment by metacosm** [comment]
Can we mount with other permissions?

**Comment by metacosm** [comment]
Also, please do not commit changes like that on master, but rather in a branch so we can test it without breaking things.

**Comment by cmoulliard** [comment]
As the user created for the folders within the image is `1001`, I'm doing a test with the following pod security context

```
SecurityContext: &corev1.PodSecurityContext{
		RunAsUser:  types.Int64P(1001),
},
```

**Comment by cmoulliard** [comment]
That resolves partially the issue as the FS is well mounted using user 1001 but folders are still owned by `root`

```
sh-4.2$ ls -la
total 24
drwxrwx---. 1 1001 root 4096 Jun 28 16:25 .
drwxr-xr-x. 1 root root 4096 Jun 28 16:25 ..
-rw-r--r--. 1 1001 root   18 May 22  2018 .bash_logout
-rw-r--r--. 1 1001 root  193 May 22  2018 .bash_profile
-rw-r--r--. 1 1001 root  231 May 22  2018 .bashrc
drwxrwxr-x. 1 1001 root 4096 Jun 28 16:25 .m2
sh-4.2$ ls -la /deployments/
total 8
drwxr-xr-x. 2 root root 4096 Aug 27 17:00 .
drwxr-xr-x. 1 root root 4096 Sep  6 12:52 ..
```

**Comment by cmoulliard** [comment]
If we don't mount using pvc the volume `/deployments`, then the permissions are correctly set to the folder

```
sh-4.2$ ls -la
total 24
drwxrwx---. 1 1001 root 4096 Jun 28 16:25 .
drwxr-xr-x. 1 root root 4096 Jun 28 16:25 ..
-rw-r--r--. 1 1001 root   18 May 22  2018 .bash_logout
-rw-r--r--. 1 1001 root  193 May 22  2018 .bash_profile
-rw-r--r--. 1 1001 root  231 May 22  2018 .bashrc
drwxrwxr-x. 1 1001 root 4096 Jun 28 16:25 .m2
sh-4.2$ ls -la /deployments/
total 9004
drwxrwxr-x. 1 jboss root    4096 Sep  6 13:29 .
drwxr-xr-x. 1 root  root    4096 Sep  6 13:28 ..
drwxrwxr-x. 2 jboss root    4096 Jun 28 16:25 data
-rw-r--r--. 1  1001 root 9205248 Sep  6 13:29 fruit-backend-sb-0.0.1-SNAPSHOT.jar
```

**Comment by cmoulliard** [comment]
Remark. When your cluster has been configured using as PersistentVolume [HostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath), then it is mandatory to chown of the path mounted (e.g /tmp/pv001, /tmp/pv002,...)in order to avoid that `root` user is used otherwise a permission denied will take place when the uberjar files will be uploaded within the pod under the directory `/deployments`
