### ISSUE TITLE
resyncPeriod for the operator ?

### ISSUE THREAD

**Issue by pdettori** [halkyonio/operator#159]
I have run the demo, and after applying the Halkyon resources, I see the following the behavior:

```
oc get cp -n demo
NAME               RUNTIME       VERSION         AGE       MODE      STATUS    MESSAGE   REVISION
fruit-backend-sb   spring-boot   2.1.6.RELEASE   2m23s     dev       Ready     Ready
fruit-client-sb    spring-boot   2.1.6.RELEASE   2m33s     dev       Ready     Ready
```
But:

```
oc get links -n demo
NAME                    AGE       STATUS    MESSAGE
link-to-database        2m39s     Pending   component is not ready for Link 'link-to-database' in namespace 'demo'
link-to-fruit-backend   2m49s     Pending   component is not ready for Link 'link-to-fruit-backend' in namespace 'demo'
```

the links stay in pending status for several minutes, and eventually I restarted the Halkyon operator pod to trigger resync:

```
$ k delete pod -n operators halkyon-operator-78fb78b5df-52bcz
pod "halkyon-operator-78fb78b5df-52bcz" deleted

$ k get pods -n operators
NAME                                READY   STATUS    RESTARTS   AGE
halkyon-operator-78fb78b5df-bptvz   1/1     Running   0          10s

$ oc get links -n demo
NAME                    AGE       STATUS    MESSAGE
link-to-database        3m36s     Ready     Ready
link-to-fruit-backend   3m46s     Ready     Ready
```

Looking at the code, the `resyncPeriod` is not set in the watchers. The controller-runtime default is 10hrs, which I think is used by operator-sdk as well as default.

**Comment by cmoulliard** [comment]
Do you think @metacosm that we could configure the resyncPeriod as proposed by @pdettori  and documented here - https://github.com/operator-framework/operator-sdk-samples/blob/master/vault-operator/cmd/vault-operator/main.go#L33-L35 ?

**Comment by cmoulliard** [comment]
BTW, the sdk.watch is not longer used as now operator-sdk relies on controller-runtime and I dont think that we can still configure this parameter ....

**Comment by pdettori** [comment]
operator-sdk is using controller-runtime and controller manager. The manager (https://github.com/operator-framework/getting-started/blob/master/README.md#manager ) does have the syncPeriod option (https://github.com/kubernetes-sigs/controller-runtime/blob/801e12a501606245062a6ff77ac91eef8936d9fb/pkg/manager/manager.go#L107 ). It should be provided with the options when creating a new Manager. You are right that it is no longer provided with the Watch().

**Comment by pdettori** [comment]
So I think that the change should be something like:
```
	syncPeriod := 30 * time.Second 
       // check if we want to watch a single namespace
	namespace, found := os.LookupEnv(WatchNamespaceEnvVar)
	options := manager.Options{}
	if found {
		options.Namespace = namespace
		options.SyncPeriod = &syncPeriod
		log.Info("watching namespace " + namespace)
	}
      // Create a new Cmd to provide shared dependencies and start components
	mgr, err := manager.New(config.GetConfigOrDie(), options)
	if err != nil {
		log.Error(err, "")
	}
```
in main.go

**Comment by metacosm** [comment]
While using `syncPeriod` might indeed solve things, I think the underlying is elsewhere, either the links should be re-queued so that their status is updated and they're not or something else… It seems like decreasing the re-synching period would only hide the real issue…

**Comment by pdettori** [comment]
Re-queueing sounds like a good approach here for links. I would still consider if making `syncPeriod` smaller then the default used in `controller-runtime` (which I think it's 10 hrs). Since the halkyon operator is managing underlying resources such as deployments and CRDs from other operators (e.g. KubeDB) it might be good to reflect the status of the underlying resources into the halkyon resources if some resource becomes unavailable or it's deleted externally (what happens if someone deletes the DB or a deployment created by halkyon out-of-band ?)

**Comment by metacosm** [comment]
@pdettori I will look into decreasing the sync period, since I agree with you that it would still be a good idea 👍

**Comment by pdettori** [comment]
Sounds good, thank you @metacosm

**Comment by cmoulliard** [comment]
> I will look into decreasing the sync period, since I agree with you that it would still be a good idea

Is it done ? @metacosm

**Comment by pdettori** [comment]
@metacosm thanks, I just tested and it works for me now !

```
$ kubectl apply -f ./demo/fruit-backend-sb/target/classes/META-INF/dekorate/halkyon.yml -n demo
capability.halkyon.io/postgres-db created
component.halkyon.io/fruit-backend-sb created
link.halkyon.io/link-to-database created
$ k get cp,link,capability -n demo
NAME                                    RUNTIME       VERSION         AGE   MODE   STATUS   MESSAGE   REVISION
component.halkyon.io/fruit-backend-sb   spring-boot   2.1.6.RELEASE   18s   dev    Ready    Ready
component.halkyon.io/fruit-client-sb    spring-boot   2.1.6.RELEASE   19s   dev    Ready    Ready

NAME                                    AGE   STATUS   MESSAGE
link.halkyon.io/link-to-database        18s   Ready    Ready
link.halkyon.io/link-to-fruit-backend   19s   Ready    Ready

NAME                                CATEGORY   KIND       AGE   STATUS   MESSAGE   REVISION
capability.halkyon.io/postgres-db   database   postgres   18s   Ready    Ready
```
