### ISSUE TITLE
[Doc]: use “minikube ip” to get the address of minikube for ingress

### ISSUE THREAD

**Issue by pdettori** [halkyonio/operator#160]
I have run the demo and found that there is a hardcoded IP for minikube in the instructions. The minikube IP can be found with `minikube ip`. 

So Instead of using:

```
export FRONTEND_ROUTE_URL=195.201.87.126
```

I suggest using:
```
export FRONTEND_ROUTE_URL=$(minikube ip)
```

and for MiniShift :

```
export FRONTEND_ROUTE_URL=fruit-client-sb-test.$(minikube ip).nip.io 
```

**Comment by cmoulliard** [comment]
I propose that we add then before the examples a comment mentioning that the IP address could be found using either `minishift ip` or `minikube ip` as such commands could also be executed on a cluster not created using one of these tools

**Comment by cmoulliard** [comment]
I fixed the doc. Can you review and close if the problem is fixed please ? @pdettori

**Comment by pdettori** [comment]
@cmoulliard looks good, thx.
