### ISSUE TITLE
[Doc]: Use file paths more consistently in demo instructions

### ISSUE THREAD

**Issue by pdettori** [halkyonio/operator#161]
In the demo instructions, sometimes commands are run from the project home and sometimes from inside the project folder. It would be good to run them all from one place (e.g. project home):

e.g.

```
mvn clean package -f demo
``` 
or

```
./demo/scripts/k8s_push_start.sh fruit-backend sb demo
./demo/scripts/k8s_push_start.sh fruit-client sb demo
```

and

```
kubectl apply -f fruit-client-sb/target/classes/META-INF/dekorate/halkyon.yml
kubectl apply -f fruit-backend-sb/target/classes/META-INF/dekorate/halkyon.yml
```

**Comment by cmoulliard** [comment]
Great remark ;-)

**Comment by cmoulliard** [comment]
PR merged. Can you please confirm if we could close this issue @pdettori ?

**Comment by pdettori** [comment]
It looks good, thx
