### ISSUE TITLE
Component API comments

### ISSUE THREAD

**Issue by metacosm** [halkyonio/operator#18]
Generally speaking, as this is meant to be an API, anything pertaining to implementation details should be hidden. That means no `SupervisordName`  field. The exposed fields should be as few as possible to start with since it's easier to add things later on when it's proven that they're needed than to remove them if we figure out that they're not (e.g. `hotReload` and `PackagingMode` that don't look like they're used at all should be removed). More structure would be helpful as well (e.g. a struct to encapsulate runtime details).

**Comment by geoand** [comment]
This opens a good discussion since on one hand we want few fields to make everything clean, on the other hand there are plenty of scenarios where extra configuration will be needed for the specific use case to work

**Comment by cmoulliard** [comment]
Is there a way to encapsulate and hide in golang such internal fields ? @geoand @metacosm

**Comment by geoand** [comment]
You mean have a struct were some members are exposed and others are not?
Usually having fields lowercase will mean that the fields are not visible outside the package, but I don't know if that works with unmarshalling

**Comment by cmoulliard** [comment]
This is the purpose of my question. Can we avoid that some fields are marshalled and next included within the json/yaml response generated ?

**Comment by geoand** [comment]
@cmoulliard I looks like it's possible: https://stackoverflow.com/a/22706984/2504224

**Comment by cmoulliard** [comment]
`omitempty` is only working in one direction. I will have a look if using a pointer could resolve the problem. We need a small project + yaml test to validate the proposition ...

**Comment by metacosm** [comment]
Yes, if a field does not start with an upper-case letter, it will not be marshalled. Only exported fields are marshalled.

**Comment by cmoulliard** [comment]
I will for the moment change the first Upper-case letter of the following fields to lower-case

- runtimeName
- supervisordName
- storage
- images

**Comment by metacosm** [comment]
The idea, though, would be to separate this information from the public API but I guess it's not that urgent.

**Comment by cmoulliard** [comment]
We could close this ticket @metacosm ?
