### ISSUE TITLE
CrashLoopBackOff in MicroK8s

### ISSUE THREAD

**Issue by jponge** [halkyonio/operator#183]
I could not manage to get the operator to work under [MicroK8s](https://microk8s.io/), I get the following `CrashLoopBackOff` error:

```
NAME                               READY   STATUS             RESTARTS   AGE
halkyon-operator-66d65cb5b-kmc9c   0/1     CrashLoopBackOff   4          117s
```

**Comment by jponge** [comment]
My bad, it works fine after all 😉

**Comment by metacosm** [comment]
That's my kind of issue! 😁
