### ISSUE TITLE
Split the API from the implementation

### ISSUE THREAD

**Issue by metacosm** [halkyonio/operator#19]
Extract the API into a separate project so that it can be imported by itself without having to import the whole operator.

**Comment by geoand** [comment]
When we say API, what do we mean exactly?

**Comment by metacosm** [comment]
Whatever entities that allow users to create / edit / marshall / unmarshall components. I.e. the model, not the whole operator machinery.

**Comment by geoand** [comment]
Thanks.

Could we in that case just use the proper golang package structure? 
Are operators generally split in the fashion you mention?

**Comment by metacosm** [comment]
> Could we in that case just use the proper golang package structure?
Not sure what you mean by that but (as far as I'm aware) when you use a dependency tool, you import the whole github project, pulling all of its transitive dependencies.

> Are operators generally split in the fashion you mention?
No idea … :)

**Comment by cmoulliard** [comment]
Can we close this issue @metacosm ?

**Comment by metacosm** [comment]
Well, I think it's still needed at some point so I'd rather keep it open for now.

**Comment by cmoulliard** [comment]
Done
