### ISSUE TITLE
Make sure that the operator gracefully handles a runtime not being available

### ISSUE THREAD

**Issue by metacosm** [halkyonio/operator#195]
Since runtimes can be deployed/removed dynamically, we need to make sure that the operator can properly react to new runtimes being made available or removed. In particular, what should happen to components using a runtime that is removed?
/cc @cmoulliard

**Comment by cmoulliard** [comment]
> what should happen to components using a runtime that is removed?

For such a problem, we must think about a way to communicate to the user (status, ....) to provide the accurate information such as this runtime is deprecated and will be removed in a next major version. Alternative could also be that we strictly validate the component deployed and if the runtime is not supported anymore, then the component will not be deployed
