### ISSUE TITLE
Update CircleCi Job

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#86]
## To Do

Concerning CircleCI, there are different things to be done:

- [x] Review existing steps and how we setup the job using ocp orb according to what is needed hereafter
- [x] Add a new step or Job using the end to end test case created under `demo/scripts/end-to-end_fruit_demo.sh` 
- [x] Customize this e2e step/job to test a deployment using `dev` OR `build` mode on k8s OR OCP => 4 tests
- [x] Discuss with the team the pertinence to create an CircleCi orb for k8s OR to use instead our  existing Ansible Playbook to setup OCP / K8s and next install the different roles such as tekton, component operator, CRDs, KubeDB [1]
- [x] Review job or step in order to `mvn compile` the `demo fruits` project to use the files generated by dekorate when capability will be available instead of the hard coded k8s resurces defined within the current bash script

[1] https://github.com/snowdrop/openshift-infra/tree/master/ansible

**Remarks** :  
- If k8s or ocp have been configured (= https://195.201.87.126:8443/console/ cluster for ocp and http://ocp4-console.10.0.76.186.nip.io/ for K8s) with Tekton and KubeDB, then you can test manually the e2e script

```
 ./demo/scripts/end-to-end_fruit_demo.sh 10.0.76.186 test dev
 ./demo/scripts/end-to-end_fruit_demo.sh 10.0.76.186 test build
```
- The `.circleci/config_demo.yml` file contains logic to setup a k8s cluster and install tekton + kubedb
- Operator can be launched locally using this command
```
cd $GOPATH/src
mkdir -p github.com/snowdrop && cd github.com/snowdrop/
git clone git@github.com:snowdrop/component-operator.git && cd component-operator
go build -o component-operator ./cmd/manager/main.go
WATCH_NAMESPACE=<NAMESPACE>
./component-operator --zap-encoder=console --kubeconfig=<K8S_CONFIG.YAML>
```

**Comment by cmoulliard** [comment]
Is the `dev` and `build` e2e working ? Can you remove hard coded yaml to use what dekorate generates ? @gytis

**Comment by gytis** [comment]
As I mentioned on Friday, build mode is not working yet. It's getting stuck for some reason. I'll debug it today.

**Comment by gytis** [comment]
@cmoulliard which version of Dekorate is needed to generate correct yaml files?

**Comment by cmoulliard** [comment]
dekorate `0.7.2` should be good. Make first a test against hetzner using the modified bash script @gytis

**Comment by cmoulliard** [comment]
k8s build mode is still not working but that could be fixed later when we will use `kind` tool with a k8s ORB
