### ISSUE TITLE
Discuss community name of the project

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#99]
## Discussion

What should be the community name of this project that we will also include within the CRD Group

Example: `capabilities.konstruct.snowdrop.dev`

List of propositions: 

- konstruct
- komposer -> can't be used as DNS name + website already exist
- mantikor
- komponent
- halkyon
- kubecomposer
- kubekomposer
- kaliper
- mantikor
- aniksi

**Comment by aureamunoz** [comment]
How do we vote?
Here is my preferences:
    konstruct
    komposer - 2
    mantikor
    komponent 
    halkyon - 1
    kubecomposer
    kubekomposer - 3

**Comment by cmoulliard** [comment]
halkyon - 1  : DNS name not registered for halkyon.io and https://github.com/halkyonio available
kubekomposer - 2 : DNS name not registered forkubekomposer.io https://github.com/kubekomposer or https://github.com/kubekomposerio available

**Comment by nainaz** [comment]
kubekomposer: 1
halkyon-2
komposer-3

**Comment by cmoulliard** [comment]
We can't use komposer as dns name, web site already exist: http://komposer.io/ !!!

**Comment by nainaz** [comment]
> We can't use komposer as dns name, web site already exist: http://komposer.io/ !!!

Changed my choice then.

**Comment by cmoulliard** [comment]
Can you vote @gytis @iocanel @metacosm @geoand ?

**Comment by geoand** [comment]
1 - Halkyon
2 - Kaliper
3 - Aniksi

**Comment by metacosm** [comment]
> We can't use komposer as dns name, web site already exist: http://komposer.io/ !!!

komposer.dev doesn't exist. I don't think that we should limit ourselves to .io TLD…

**Comment by metacosm** [comment]
1. Konstruct
2. Halkyon
3. Kaliper

**Comment by cmoulliard** [comment]
Winner is --> `Halkyon`
